In [1]:
import pandas as pd
df = pd.read_csv('data/gold_match.csv')
df['match_date'] = pd.to_datetime(df['match_date'])
df['day_of_week'] = df['match_date'].dt.day_name()
df_home = df[df["is_home_match"] == True]
df.head(10)

,match_id,match_date,kickoff_time_local,match_date_utc,kickoff_time_utc,matchday,competition_id,competition_name,season,season_id,...,winner,result_home,goals_home_ht,goals_away_ht,goals_home_ft,goals_away_ft,is_home_match,last_result_vs_opponent,tickets_scanned,day_of_week
0,d0te6swsv2y99ywgugc2utbmc,2022-07-23,18:15:00,2022-07-23Z,16:15:00Z,1.0,4zwgbb66rif2spcoeeol2motx,Belgian Jupiler Pro League,2022/2023,5wj8l9y4s3484k6puwup793pw,...,away,L,0,0,0,2,False,L 1-2,NaN,Saturday
1,d256yo3eng04m0fu7b4sl7wno,2022-07-30,18:15:00,2022-07-30Z,16:15:00Z,2.0,4zwgbb66rif2spcoeeol2motx,Belgian Jupiler Pro League,2022/2023,5wj8l9y4s3484k6puwup793pw,...,home,W,1,0,2,0,True,NaN,5565.0,Saturday
2,d3pqkck2grzx98jg4sofhp8us,2022-08-07,21:00:00,2022-08-07Z,19:00:00Z,3.0,4zwgbb66rif2spcoeeol2motx,Belgian Jupiler Pro League,2022/2023,5wj8l9y4s3484k6puwup793pw,...,home,W,2,1,4,2,False,L 0-1,NaN,Sunday
3,d4mn5ksbxuvnaww4pmommxhqs,2022-08-14,18:30:00,2022-08-14Z,16:30:00Z,4.0,4zwgbb66rif2spcoeeol2motx,Belgian Jupiler Pro League,2022/2023,5wj8l9y4s3484k6puwup793pw,...,away,L,0,2,0,3,True,L 1-4,7440.0,Sunday
4,d5htdqmc8w72upys41sfxhfkk,2022-08-21,18:30:00,2022-08-21Z,16:30:00Z,5.0,4zwgbb66rif2spcoeeol2motx,Belgian Jupiler Pro League,2022/2023,5wj8l9y4s3484k6puwup793pw,...,away,L,0,2,1,3,False,W 2-1,NaN,Sunday
5,d65hmi7sq03yzr5he1k7ypus4,2022-08-27,18:15:00,2022-08-27Z,16:15:00Z,6.0,4zwgbb66rif2spcoeeol2motx,Belgian Jupiler Pro League,2022/2023,5wj8l9y4s3484k6puwup793pw,...,home,W,0,1,2,1,True,W 3-1,4489.0,Saturday
6,d700mwu32x772ns4veqq32yhg,2022-09-04,13:30:00,2022-09-04Z,11:30:00Z,7.0,4zwgbb66rif2spcoeeol2motx,Belgian Jupiler Pro League,2022/2023,5wj8l9y4s3484k6puwup793pw,...,draw,D,0,1,2,2,False,D 0-0,NaN,Sunday
7,d80mkemezkz16bqh6lbn8tlhw,2022-09-10,20:45:00,2022-09-10Z,18:45:00Z,8.0,4zwgbb66rif2spcoeeol2motx,Belgian Jupiler Pro League,2022/2023,5wj8l9y4s3484k6puwup793pw,...,home,W,1,1,3,2,True,W 3-0,4508.0,Saturday
8,d9pbl588401et3engzzakcfmc,2022-09-17,16:00:00,2022-09-17Z,14:00:00Z,9.0,4zwgbb66rif2spcoeeol2motx,Belgian Jupiler Pro League,2022/2023,5wj8l9y4s3484k6puwup793pw,...,draw,D,0,0,0,0,False,L 0-2,NaN,Saturday
9,dak40etbhbqsr1nxyt50qcg0k,2022-10-01,16:00:00,2022-10-01Z,14:00:00Z,10.0,4zwgbb66rif2spcoeeol2motx,Belgian Jupiler Pro League,2022/2023,5wj8l9y4s3484k6puwup793pw,...,away,L,0,2,0,3,True,L 1-4,6290.0,Saturday

group the teams into top 6 individual and mid, bottom 6 in groups

In [11]:
team_avg = (
    df_home
    .groupby("away_team")["tickets_scanned"]
    .mean()
    .reset_index()
    .rename(columns={"tickets_scanned": "avg_tickets"})
)

team_avg = team_avg.sort_values(by="avg_tickets", ascending=False)

top_6 = team_avg.iloc[:6].copy()
middle_6 = team_avg.iloc[6:12].copy()
bottom_6 = team_avg.iloc[12:18].copy()

# Individual labels
top_6["group"] = top_6["away_team"]

# Grouped labels
middle_6["group"] = "middle_6"
bottom_6["group"] = "bottom_6"

final_groups = pd.concat([top_6, middle_6, bottom_6])

final_groups.head(18)

               away_team  avg_tickets           group
0             Anderlecht  9828.250000      Anderlecht
4            Club Brugge  9115.750000     Club Brugge
1                Antwerp  8276.333333         Antwerp
13                  RWDM  7786.000000            RWDM
17        Standard Liège  7500.166667  Standard Liège
11              Mechelen  7380.833333        Mechelen
18  Union Saint-Gilloise  6936.250000        middle_6
7                   Genk  6756.750000        middle_6
8                   Gent  6724.600000        middle_6
2              Beerschot  6655.000000        middle_6
19              Westerlo  6482.666667        middle_6
15          Sint-Truiden  6376.600000        middle_6
10              Kortrijk  6323.666667        bottom_6
20         Zulte Waregem  6139.500000        bottom_6
3          Cercle Brugge  6024.750000        bottom_6
6                  Eupen  5700.000000        bottom_6
16    Sporting Charleroi  5587.200000        bottom_6
14               Seraing  5285.000000        bottom_6